steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/app:latest
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/app:latest

substitutions:
  _ARTIFACT_REGISTRY_LOCATION: us-west1
  _REPO_NAME: immiaubot
